version: '3.8'

services:
  # Game client (frontend)
  game-client:
    build: .
    ports:
      - "8080:80"
    environment:
      - VITE_MULTIPLAYER_SERVER_URL=ws://localhost:3001
    depends_on:
      - multiplayer-server
    networks:
      - game-network

  # Multiplayer server (optional)
  multiplayer-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - game-network

networks:
  game-network:
    driver: bridge