name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get version from tag
        id: get_version
        run: |
          git fetch --tags --force
          export VERSION=$(git describe --tags --abbrev=0)
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: VITE_BASE_PATH=/generated-game-experiment/ npm run build
      - run: ls -l
      - run: ls -l dist
      - run: touch dist/.keep
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist