name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: VITE_BASE_PATH=/generated-game-experiment/ npm run build
      - run: ls -l
      - run: ls -l dist
      - run: touch dist/.keep
      - name: Fetch full git history for version injection
        run: git fetch --unshallow || true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist